// theme.js
export const lightMode = {
    background: '#f9f9f9',
    text: '#333',
    appBar: '#fff',
    tabActive: '#e0e0e0',
    tabInactive: '#f0f0f0',
    card: '#fff',
    buttonPrimary: '#3b82f6',
    buttonPrimaryText: '#fff',
    buttonSecondary: '#ef4444',
    buttonSecondaryText: '#fff',
    buttonError: '#f97316',
    buttonErrorText: '#fff',
    tabTextActive: '#222',
    tabTextInactive: '#555',
    cardBackground: '#fff',
    cardContentBackground: '#fff',
    inputBackground: '#fff',
    inputBorder: '#ccc',
    inputTextColor: '#333',
};

export const darkMode = {
    background: '#121212',
    text: '#eee',
    appBar: '#1e1e1e',
    tabActive: '#333',
    tabInactive: '#272727',
    card: '#222',
    buttonPrimary: '#60a5fa',
    buttonPrimaryText: '#fff',
    buttonSecondary: '#f44336',
    buttonSecondaryText: '#fff',
    buttonError: '#ff9800',
    buttonErrorText: '#fff',
    tabTextActive: '#eee',
    tabTextInactive: '#bbb',
    cardBackground: '#222',
    cardContentBackground: '#222',
    inputBackground: '#333',
    inputBorder: '#555',
    inputTextColor: '#eee',
};