name: Publish Package to NPM

on:
  push:
    tags:
      - 'easya-react@*'
      - 'easya-sdk-core@*'
      - 'raouf-test-package@*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Get package info
        id: package
        run: |
          PACKAGE_NAME=$(echo ${{ github.ref_name }} | cut -d@ -f1)
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: |
          cd packages/${{ env.PACKAGE_NAME }}
          npm ci
          
      - name: Build
        run: |
          cd packages/${{ env.PACKAGE_NAME }}
          npm run build
          
      - name: Publish to NPM
        run: |
          cd packages/${{ env.PACKAGE_NAME }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}